language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - apt-get install python-wxgtk2.8
    - cd taskcoach
    - make prepare
    - python taskcoach.py
# command to run tests
script: 
    - cd taskcoach
    - make unittests